# This file is meant for running a production build IN A DEPLOYMENT

version: '3'

services:
  client:
    image: cokoapps/ketty-client-deploy-develop:latest
    ports:
      - ${CLIENT_PORT}:8080
    environment:
      - SERVER_URL=${SERVER_URL}
      - WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL}

  server:
    image: cokoapps/ketty-server:latest
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:3000
      - ${WS_SERVER_PORT}:3333
    environment:
      - NODE_ENV=production
      - KETIDA_FLAVOUR=LULU
      - PUBSWEET_SECRET=${PUBSWEET_SECRET}
      - SERVER_URL=${SERVER_URL}
      - WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL}
      - CLIENT_URL=${CLIENT_URL}
      - SERVER_SERVE_CLIENT=false
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - WS_HEARTBEAT_INTERVAL=${WS_HEARTBEAT_INTERVAL}
      - FAIL_SAFE_UNLOCKING_INTERVAL=${FAIL_SAFE_UNLOCKING_INTERVAL}
      - MAILER_USER=${MAILER_USER}
      - MAILER_PASSWORD=${MAILER_PASSWORD}
      - MAILER_SENDER=${MAILER_SENDER}
      - MAILER_HOSTNAME=${MAILER_HOSTNAME}
      - PASSWORD_RESET_PATH_TO_PAGE=/password-reset
      - S3_PROTOCOL=${S3_PROTOCOL}
      - S3_HOST=${S3_HOST}
      - S3_PORT=${S3_PORT}
      - S3_ACCESS_KEY_ID_USER=${S3_ACCESS_KEY_ID_USER}
      - S3_SECRET_ACCESS_KEY_USER=${S3_SECRET_ACCESS_KEY_USER}
      - S3_BUCKET=${S3_BUCKET}
      - SERVICE_EPUB_CHECKER_CLIENT_ID=${SERVICE_EPUB_CHECKER_CLIENT_ID}
      - SERVICE_EPUB_CHECKER_SECRET=${SERVICE_EPUB_CHECKER_SECRET}
      - SERVICE_EPUB_CHECKER_URL=${SERVICE_EPUB_CHECKER_URL}
      - SERVICE_PAGEDJS_CLIENT_ID=${SERVICE_PAGEDJS_CLIENT_ID}
      - SERVICE_PAGEDJS_SECRET=${SERVICE_PAGEDJS_SECRET}
      - SERVICE_PAGEDJS_URL=${SERVICE_PAGEDJS_URL}
      - SERVICE_XSWEET_CLIENT_ID=${SERVICE_XSWEET_CLIENT_ID}
      - SERVICE_XSWEET_SECRET=${SERVICE_XSWEET_SECRET}
      - SERVICE_XSWEET_URL=${SERVICE_XSWEET_URL}
      - FEATURE_UPLOAD_DOCX_FILES=true
      - FEATURE_BOOK_STRUCTURE=false
      - FEATURE_POD=true
      - TEMP_DIRECTORY_CRON_JOB_SCHEDULE=${TEMP_DIRECTORY_CRON_JOB_TIMING}
      - TEMP_DIRECTORY_CRON_JOB_OFFSET=${TEMP_DIRECTORY_CRON_JOB_OFFSET}
      - TEMP_DIRECTORY_CLEAN_UP=${TEMP_DIRECTORY_CLEAN_UP:-true}
      - AI_ENABLED=${AI_ENABLED}
      - CHAT_GPT_KEY=${CHAT_GPT_KEY}
    volumes:
      - ./config/local.js:/home/node/server/config/local.js
      - ./config/termsAndConditions.md:/home/node/server/config/termsAndConditions.md
